# Generated by Django 5.2.8 on 2025-11-12 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('traders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
